/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppConfigDto,
} from '../models/index';
import {
    AppConfigDtoFromJSON,
    AppConfigDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class AppApi extends runtime.BaseAPI {

    /**
     */
    async getAppConfigRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppConfigDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/App/config`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppConfigDtoFromJSON(jsonValue));
    }

    /**
     */
    async getAppConfig(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppConfigDto> {
        const response = await this.getAppConfigRaw(initOverrides);
        return await response.value();
    }

}
