/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateExampleCommand,
  ExampleDto,
  ProblemDetails,
} from '../models/index';
import {
    CreateExampleCommandFromJSON,
    CreateExampleCommandToJSON,
    ExampleDtoFromJSON,
    ExampleDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreateExampleRequest {
    createExampleCommand?: CreateExampleCommand;
}

/**
 * 
 */
export class ExampleApi extends runtime.BaseAPI {

    /**
     */
    async createExampleRaw(requestParameters: CreateExampleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExampleDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Example`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExampleCommandToJSON(requestParameters['createExampleCommand']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExampleDtoFromJSON(jsonValue));
    }

    /**
     */
    async createExample(requestParameters: CreateExampleRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExampleDto> {
        const response = await this.createExampleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getExamplesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExampleDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Example`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExampleDtoFromJSON));
    }

    /**
     */
    async getExamples(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExampleDto>> {
        const response = await this.getExamplesRaw(initOverrides);
        return await response.value();
    }

}
