/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BatchDto,
  JourneyCoordinatesDto,
  JourneyEventDto,
  PointToPointRouteDto,
  ProblemDetails,
  ProductDto,
  ProductSummaryDto,
  RouteDto,
} from '../models/index';
import {
    BatchDtoFromJSON,
    BatchDtoToJSON,
    JourneyCoordinatesDtoFromJSON,
    JourneyCoordinatesDtoToJSON,
    JourneyEventDtoFromJSON,
    JourneyEventDtoToJSON,
    PointToPointRouteDtoFromJSON,
    PointToPointRouteDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ProductDtoFromJSON,
    ProductDtoToJSON,
    ProductSummaryDtoFromJSON,
    ProductSummaryDtoToJSON,
    RouteDtoFromJSON,
    RouteDtoToJSON,
} from '../models/index';

export interface GetBatchByIdRequest {
    batchId: string;
}

export interface GetBatchRouteRequest {
    batchId: string;
}

export interface GetPointToPointRouteRequest {
    fromLat?: number;
    fromLon?: number;
    toLat?: number;
    toLon?: number;
    profile?: string;
}

export interface GetProductByGtinRequest {
    gtin: string;
}

export interface GetProductByIdRequest {
    id: string;
}

export interface GetProductCoordinatesRequest {
    id: string;
}

export interface GetProductJourneyRequest {
    id: string;
}

export interface LookupBatchRequest {
    gtin?: string;
    lot?: string;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     */
    async getBatchByIdRaw(requestParameters: GetBatchByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchDto>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling getBatchById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/batch/{batchId}`.replace(`{${"batchId"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchDtoFromJSON(jsonValue));
    }

    /**
     */
    async getBatchById(requestParameters: GetBatchByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchDto> {
        const response = await this.getBatchByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBatchRouteRaw(requestParameters: GetBatchRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RouteDto>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling getBatchRoute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/batch/{batchId}/route`.replace(`{${"batchId"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RouteDtoFromJSON(jsonValue));
    }

    /**
     */
    async getBatchRoute(requestParameters: GetBatchRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RouteDto> {
        const response = await this.getBatchRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPointToPointRouteRaw(requestParameters: GetPointToPointRouteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PointToPointRouteDto>> {
        const queryParameters: any = {};

        if (requestParameters['fromLat'] != null) {
            queryParameters['fromLat'] = requestParameters['fromLat'];
        }

        if (requestParameters['fromLon'] != null) {
            queryParameters['fromLon'] = requestParameters['fromLon'];
        }

        if (requestParameters['toLat'] != null) {
            queryParameters['toLat'] = requestParameters['toLat'];
        }

        if (requestParameters['toLon'] != null) {
            queryParameters['toLon'] = requestParameters['toLon'];
        }

        if (requestParameters['profile'] != null) {
            queryParameters['profile'] = requestParameters['profile'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/route`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PointToPointRouteDtoFromJSON(jsonValue));
    }

    /**
     */
    async getPointToPointRoute(requestParameters: GetPointToPointRouteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PointToPointRouteDto> {
        const response = await this.getPointToPointRouteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductByGtinRaw(requestParameters: GetProductByGtinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDto>> {
        if (requestParameters['gtin'] == null) {
            throw new runtime.RequiredError(
                'gtin',
                'Required parameter "gtin" was null or undefined when calling getProductByGtin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/gtin/{gtin}`.replace(`{${"gtin"}}`, encodeURIComponent(String(requestParameters['gtin']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDtoFromJSON(jsonValue));
    }

    /**
     */
    async getProductByGtin(requestParameters: GetProductByGtinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDto> {
        const response = await this.getProductByGtinRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductByIdRaw(requestParameters: GetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductDtoFromJSON(jsonValue));
    }

    /**
     */
    async getProductById(requestParameters: GetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductDto> {
        const response = await this.getProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductCoordinatesRaw(requestParameters: GetProductCoordinatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JourneyCoordinatesDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProductCoordinates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/{id}/coordinates`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JourneyCoordinatesDtoFromJSON(jsonValue));
    }

    /**
     */
    async getProductCoordinates(requestParameters: GetProductCoordinatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JourneyCoordinatesDto> {
        const response = await this.getProductCoordinatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductJourneyRaw(requestParameters: GetProductJourneyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<JourneyEventDto>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProductJourney().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/{id}/journey`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(JourneyEventDtoFromJSON));
    }

    /**
     */
    async getProductJourney(requestParameters: GetProductJourneyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<JourneyEventDto>> {
        const response = await this.getProductJourneyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductSummaryDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductSummaryDtoFromJSON));
    }

    /**
     */
    async getProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductSummaryDto>> {
        const response = await this.getProductsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async lookupBatchRaw(requestParameters: LookupBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchDto>> {
        const queryParameters: any = {};

        if (requestParameters['gtin'] != null) {
            queryParameters['gtin'] = requestParameters['gtin'];
        }

        if (requestParameters['lot'] != null) {
            queryParameters['lot'] = requestParameters['lot'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Product/batch/lookup`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchDtoFromJSON(jsonValue));
    }

    /**
     */
    async lookupBatch(requestParameters: LookupBatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchDto> {
        const response = await this.lookupBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
