/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminProductDto,
  AlertDto,
  ProblemDetails,
  ScanRecordDto,
} from '../models/index';
import {
    AdminProductDtoFromJSON,
    AdminProductDtoToJSON,
    AlertDtoFromJSON,
    AlertDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ScanRecordDtoFromJSON,
    ScanRecordDtoToJSON,
} from '../models/index';

export interface RecordScanRequest {
    gtin: string;
}

/**
 * 
 */
export class ScanApi extends runtime.BaseAPI {

    /**
     */
    async getAllAlertsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Scan/all-alerts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertDtoFromJSON));
    }

    /**
     */
    async getAllAlerts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertDto>> {
        const response = await this.getAllAlertsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllProductsWithStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminProductDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Scan/all-products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminProductDtoFromJSON));
    }

    /**
     */
    async getAllProductsWithStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminProductDto>> {
        const response = await this.getAllProductsWithStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyAlertsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AlertDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Scan/alerts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AlertDtoFromJSON));
    }

    /**
     */
    async getMyAlerts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AlertDto>> {
        const response = await this.getMyAlertsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getRecentScansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ScanRecordDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Scan/recent`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ScanRecordDtoFromJSON));
    }

    /**
     */
    async getRecentScans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ScanRecordDto>> {
        const response = await this.getRecentScansRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async recordScanRaw(requestParameters: RecordScanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScanRecordDto>> {
        if (requestParameters['gtin'] == null) {
            throw new runtime.RequiredError(
                'gtin',
                'Required parameter "gtin" was null or undefined when calling recordScan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Scan/{gtin}`.replace(`{${"gtin"}}`, encodeURIComponent(String(requestParameters['gtin']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScanRecordDtoFromJSON(jsonValue));
    }

    /**
     */
    async recordScan(requestParameters: RecordScanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScanRecordDto> {
        const response = await this.recordScanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
