/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductStatus } from './ProductStatus';
import {
    ProductStatusFromJSON,
    ProductStatusFromJSONTyped,
    ProductStatusToJSON,
    ProductStatusToJSONTyped,
} from './ProductStatus';

/**
 * 
 * @export
 * @interface AdminProductDto
 */
export interface AdminProductDto {
    /**
     * 
     * @type {string}
     * @memberof AdminProductDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AdminProductDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminProductDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdminProductDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {ProductStatus}
     * @memberof AdminProductDto
     */
    status?: ProductStatus;
}



/**
 * Check if a given object implements the AdminProductDto interface.
 */
export function instanceOfAdminProductDto(value: object): value is AdminProductDto {
    return true;
}

export function AdminProductDtoFromJSON(json: any): AdminProductDto {
    return AdminProductDtoFromJSONTyped(json, false);
}

export function AdminProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'status': json['status'] == null ? undefined : ProductStatusFromJSON(json['status']),
    };
}

export function AdminProductDtoToJSON(json: any): AdminProductDto {
    return AdminProductDtoToJSONTyped(json, false);
}

export function AdminProductDtoToJSONTyped(value?: AdminProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'brand': value['brand'],
        'imageUrl': value['imageUrl'],
        'status': ProductStatusToJSON(value['status']),
    };
}

