/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertType } from './AlertType';
import {
    AlertTypeFromJSON,
    AlertTypeFromJSONTyped,
    AlertTypeToJSON,
    AlertTypeToJSONTyped,
} from './AlertType';
import type { AlertSeverity } from './AlertSeverity';
import {
    AlertSeverityFromJSON,
    AlertSeverityFromJSONTyped,
    AlertSeverityToJSON,
    AlertSeverityToJSONTyped,
} from './AlertSeverity';

/**
 * 
 * @export
 * @interface AlertDto
 */
export interface AlertDto {
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    id?: string;
    /**
     * 
     * @type {AlertType}
     * @memberof AlertDto
     */
    type?: AlertType;
    /**
     * 
     * @type {AlertSeverity}
     * @memberof AlertDto
     */
    severity?: AlertSeverity;
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AlertDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AlertDto
     */
    read?: boolean;
}



/**
 * Check if a given object implements the AlertDto interface.
 */
export function instanceOfAlertDto(value: object): value is AlertDto {
    return true;
}

export function AlertDtoFromJSON(json: any): AlertDto {
    return AlertDtoFromJSONTyped(json, false);
}

export function AlertDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : AlertTypeFromJSON(json['type']),
        'severity': json['severity'] == null ? undefined : AlertSeverityFromJSON(json['severity']),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'read': json['read'] == null ? undefined : json['read'],
    };
}

export function AlertDtoToJSON(json: any): AlertDto {
    return AlertDtoToJSONTyped(json, false);
}

export function AlertDtoToJSONTyped(value?: AlertDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': AlertTypeToJSON(value['type']),
        'severity': AlertSeverityToJSON(value['severity']),
        'title': value['title'],
        'description': value['description'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'read': value['read'],
    };
}

