/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AlertType = {
    Recall: 'Recall',
    ColdChain: 'ColdChain',
    Expiry: 'Expiry'
} as const;
export type AlertType = typeof AlertType[keyof typeof AlertType];


export function instanceOfAlertType(value: any): boolean {
    for (const key in AlertType) {
        if (Object.prototype.hasOwnProperty.call(AlertType, key)) {
            if (AlertType[key as keyof typeof AlertType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AlertTypeFromJSON(json: any): AlertType {
    return AlertTypeFromJSONTyped(json, false);
}

export function AlertTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertType {
    return json as AlertType;
}

export function AlertTypeToJSON(value?: AlertType | null): any {
    return value as any;
}

export function AlertTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AlertType {
    return value as AlertType;
}

