/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlternativeProductDto
 */
export interface AlternativeProductDto {
    /**
     * 
     * @type {string}
     * @memberof AlternativeProductDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AlternativeProductDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlternativeProductDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlternativeProductDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlternativeProductDto
     */
    nutriScore?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AlternativeProductDto
     */
    co2Kg?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof AlternativeProductDto
     */
    improvementTags?: Array<string> | null;
}

/**
 * Check if a given object implements the AlternativeProductDto interface.
 */
export function instanceOfAlternativeProductDto(value: object): value is AlternativeProductDto {
    return true;
}

export function AlternativeProductDtoFromJSON(json: any): AlternativeProductDto {
    return AlternativeProductDtoFromJSONTyped(json, false);
}

export function AlternativeProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'nutriScore': json['nutriScore'] == null ? undefined : json['nutriScore'],
        'co2Kg': json['co2Kg'] == null ? undefined : json['co2Kg'],
        'improvementTags': json['improvementTags'] == null ? undefined : json['improvementTags'],
    };
}

export function AlternativeProductDtoToJSON(json: any): AlternativeProductDto {
    return AlternativeProductDtoToJSONTyped(json, false);
}

export function AlternativeProductDtoToJSONTyped(value?: AlternativeProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'brand': value['brand'],
        'imageUrl': value['imageUrl'],
        'nutriScore': value['nutriScore'],
        'co2Kg': value['co2Kg'],
        'improvementTags': value['improvementTags'],
    };
}

