/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ColdChainAnomalyDto } from './ColdChainAnomalyDto';
import {
    ColdChainAnomalyDtoFromJSON,
    ColdChainAnomalyDtoFromJSONTyped,
    ColdChainAnomalyDtoToJSON,
    ColdChainAnomalyDtoToJSONTyped,
} from './ColdChainAnomalyDto';

/**
 * 
 * @export
 * @interface AnomalyDetectionResultDto
 */
export interface AnomalyDetectionResultDto {
    /**
     * 
     * @type {Array<ColdChainAnomalyDto>}
     * @memberof AnomalyDetectionResultDto
     */
    anomalies?: Array<ColdChainAnomalyDto> | null;
    /**
     * 
     * @type {string}
     * @memberof AnomalyDetectionResultDto
     */
    overallRisk?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AnomalyDetectionResultDto
     */
    chainIntegrityScore?: number;
}

/**
 * Check if a given object implements the AnomalyDetectionResultDto interface.
 */
export function instanceOfAnomalyDetectionResultDto(value: object): value is AnomalyDetectionResultDto {
    return true;
}

export function AnomalyDetectionResultDtoFromJSON(json: any): AnomalyDetectionResultDto {
    return AnomalyDetectionResultDtoFromJSONTyped(json, false);
}

export function AnomalyDetectionResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnomalyDetectionResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'anomalies': json['anomalies'] == null ? undefined : ((json['anomalies'] as Array<any>).map(ColdChainAnomalyDtoFromJSON)),
        'overallRisk': json['overallRisk'] == null ? undefined : json['overallRisk'],
        'chainIntegrityScore': json['chainIntegrityScore'] == null ? undefined : json['chainIntegrityScore'],
    };
}

export function AnomalyDetectionResultDtoToJSON(json: any): AnomalyDetectionResultDto {
    return AnomalyDetectionResultDtoToJSONTyped(json, false);
}

export function AnomalyDetectionResultDtoToJSONTyped(value?: AnomalyDetectionResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'anomalies': value['anomalies'] == null ? undefined : ((value['anomalies'] as Array<any>).map(ColdChainAnomalyDtoToJSON)),
        'overallRisk': value['overallRisk'],
        'chainIntegrityScore': value['chainIntegrityScore'],
    };
}

