/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppConfigDto
 */
export interface AppConfigDto {
    /**
     * 
     * @type {string}
     * @memberof AppConfigDto
     */
    authority?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppConfigDto
     */
    clientId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppConfigDto
     */
    redirectUri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppConfigDto
     */
    postLogoutRedirectUri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppConfigDto
     */
    scope?: string | null;
}

/**
 * Check if a given object implements the AppConfigDto interface.
 */
export function instanceOfAppConfigDto(value: object): value is AppConfigDto {
    return true;
}

export function AppConfigDtoFromJSON(json: any): AppConfigDto {
    return AppConfigDtoFromJSONTyped(json, false);
}

export function AppConfigDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppConfigDto {
    if (json == null) {
        return json;
    }
    return {
        
        'authority': json['authority'] == null ? undefined : json['authority'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'redirectUri': json['redirectUri'] == null ? undefined : json['redirectUri'],
        'postLogoutRedirectUri': json['postLogoutRedirectUri'] == null ? undefined : json['postLogoutRedirectUri'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function AppConfigDtoToJSON(json: any): AppConfigDto {
    return AppConfigDtoToJSONTyped(json, false);
}

export function AppConfigDtoToJSONTyped(value?: AppConfigDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authority': value['authority'],
        'clientId': value['clientId'],
        'redirectUri': value['redirectUri'],
        'postLogoutRedirectUri': value['postLogoutRedirectUri'],
        'scope': value['scope'],
    };
}

