/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductStatus } from './ProductStatus';
import {
    ProductStatusFromJSON,
    ProductStatusFromJSONTyped,
    ProductStatusToJSON,
    ProductStatusToJSONTyped,
} from './ProductStatus';

/**
 * 
 * @export
 * @interface BatchSummaryDto
 */
export interface BatchSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof BatchSummaryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchSummaryDto
     */
    lotNumber?: string | null;
    /**
     * 
     * @type {ProductStatus}
     * @memberof BatchSummaryDto
     */
    status?: ProductStatus;
    /**
     * 
     * @type {number}
     * @memberof BatchSummaryDto
     */
    riskScore?: number;
    /**
     * 
     * @type {Date}
     * @memberof BatchSummaryDto
     */
    productionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BatchSummaryDto
     */
    expiryDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BatchSummaryDto
     */
    daysRemaining?: number | null;
}



/**
 * Check if a given object implements the BatchSummaryDto interface.
 */
export function instanceOfBatchSummaryDto(value: object): value is BatchSummaryDto {
    return true;
}

export function BatchSummaryDtoFromJSON(json: any): BatchSummaryDto {
    return BatchSummaryDtoFromJSONTyped(json, false);
}

export function BatchSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lotNumber': json['lotNumber'] == null ? undefined : json['lotNumber'],
        'status': json['status'] == null ? undefined : ProductStatusFromJSON(json['status']),
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'productionDate': json['productionDate'] == null ? undefined : (new Date(json['productionDate'])),
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'daysRemaining': json['daysRemaining'] == null ? undefined : json['daysRemaining'],
    };
}

export function BatchSummaryDtoToJSON(json: any): BatchSummaryDto {
    return BatchSummaryDtoToJSONTyped(json, false);
}

export function BatchSummaryDtoToJSONTyped(value?: BatchSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lotNumber': value['lotNumber'],
        'status': ProductStatusToJSON(value['status']),
        'riskScore': value['riskScore'],
        'productionDate': value['productionDate'] == null ? undefined : ((value['productionDate'] as any).toISOString()),
        'expiryDate': value['expiryDate'] == null ? undefined : ((value['expiryDate'] as any).toISOString()),
        'daysRemaining': value['daysRemaining'],
    };
}

