/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertDto } from './AlertDto';
import {
    AlertDtoFromJSON,
    AlertDtoFromJSONTyped,
    AlertDtoToJSON,
    AlertDtoToJSONTyped,
} from './AlertDto';
import type { ProductSummaryDto } from './ProductSummaryDto';
import {
    ProductSummaryDtoFromJSON,
    ProductSummaryDtoFromJSONTyped,
    ProductSummaryDtoToJSON,
    ProductSummaryDtoToJSONTyped,
} from './ProductSummaryDto';
import type { TemperatureLogDto } from './TemperatureLogDto';
import {
    TemperatureLogDtoFromJSON,
    TemperatureLogDtoFromJSONTyped,
    TemperatureLogDtoToJSON,
    TemperatureLogDtoToJSONTyped,
} from './TemperatureLogDto';
import type { PriceStepDto } from './PriceStepDto';
import {
    PriceStepDtoFromJSON,
    PriceStepDtoFromJSONTyped,
    PriceStepDtoToJSON,
    PriceStepDtoToJSONTyped,
} from './PriceStepDto';
import type { ProductStatus } from './ProductStatus';
import {
    ProductStatusFromJSON,
    ProductStatusFromJSONTyped,
    ProductStatusToJSON,
    ProductStatusToJSONTyped,
} from './ProductStatus';
import type { JourneyEventDto } from './JourneyEventDto';
import {
    JourneyEventDtoFromJSON,
    JourneyEventDtoFromJSONTyped,
    JourneyEventDtoToJSON,
    JourneyEventDtoToJSONTyped,
} from './JourneyEventDto';

/**
 * 
 * @export
 * @interface BatchDto
 */
export interface BatchDto {
    /**
     * 
     * @type {string}
     * @memberof BatchDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchDto
     */
    lotNumber?: string | null;
    /**
     * 
     * @type {ProductStatus}
     * @memberof BatchDto
     */
    status?: ProductStatus;
    /**
     * 
     * @type {number}
     * @memberof BatchDto
     */
    riskScore?: number;
    /**
     * 
     * @type {number}
     * @memberof BatchDto
     */
    shelfLifeDays?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BatchDto
     */
    daysRemaining?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BatchDto
     */
    co2Kg?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BatchDto
     */
    waterLiters?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof BatchDto
     */
    productionDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof BatchDto
     */
    expiryDate?: Date | null;
    /**
     * 
     * @type {ProductSummaryDto}
     * @memberof BatchDto
     */
    product?: ProductSummaryDto;
    /**
     * 
     * @type {Array<JourneyEventDto>}
     * @memberof BatchDto
     */
    journeyEvents?: Array<JourneyEventDto> | null;
    /**
     * 
     * @type {Array<PriceStepDto>}
     * @memberof BatchDto
     */
    priceBreakdown?: Array<PriceStepDto> | null;
    /**
     * 
     * @type {Array<TemperatureLogDto>}
     * @memberof BatchDto
     */
    temperatureLogs?: Array<TemperatureLogDto> | null;
    /**
     * 
     * @type {Array<AlertDto>}
     * @memberof BatchDto
     */
    alerts?: Array<AlertDto> | null;
}



/**
 * Check if a given object implements the BatchDto interface.
 */
export function instanceOfBatchDto(value: object): value is BatchDto {
    return true;
}

export function BatchDtoFromJSON(json: any): BatchDto {
    return BatchDtoFromJSONTyped(json, false);
}

export function BatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'lotNumber': json['lotNumber'] == null ? undefined : json['lotNumber'],
        'status': json['status'] == null ? undefined : ProductStatusFromJSON(json['status']),
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'shelfLifeDays': json['shelfLifeDays'] == null ? undefined : json['shelfLifeDays'],
        'daysRemaining': json['daysRemaining'] == null ? undefined : json['daysRemaining'],
        'co2Kg': json['co2Kg'] == null ? undefined : json['co2Kg'],
        'waterLiters': json['waterLiters'] == null ? undefined : json['waterLiters'],
        'productionDate': json['productionDate'] == null ? undefined : (new Date(json['productionDate'])),
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'product': json['product'] == null ? undefined : ProductSummaryDtoFromJSON(json['product']),
        'journeyEvents': json['journeyEvents'] == null ? undefined : ((json['journeyEvents'] as Array<any>).map(JourneyEventDtoFromJSON)),
        'priceBreakdown': json['priceBreakdown'] == null ? undefined : ((json['priceBreakdown'] as Array<any>).map(PriceStepDtoFromJSON)),
        'temperatureLogs': json['temperatureLogs'] == null ? undefined : ((json['temperatureLogs'] as Array<any>).map(TemperatureLogDtoFromJSON)),
        'alerts': json['alerts'] == null ? undefined : ((json['alerts'] as Array<any>).map(AlertDtoFromJSON)),
    };
}

export function BatchDtoToJSON(json: any): BatchDto {
    return BatchDtoToJSONTyped(json, false);
}

export function BatchDtoToJSONTyped(value?: BatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'productId': value['productId'],
        'lotNumber': value['lotNumber'],
        'status': ProductStatusToJSON(value['status']),
        'riskScore': value['riskScore'],
        'shelfLifeDays': value['shelfLifeDays'],
        'daysRemaining': value['daysRemaining'],
        'co2Kg': value['co2Kg'],
        'waterLiters': value['waterLiters'],
        'productionDate': value['productionDate'] == null ? undefined : ((value['productionDate'] as any).toISOString()),
        'expiryDate': value['expiryDate'] == null ? undefined : ((value['expiryDate'] as any).toISOString()),
        'product': ProductSummaryDtoToJSON(value['product']),
        'journeyEvents': value['journeyEvents'] == null ? undefined : ((value['journeyEvents'] as Array<any>).map(JourneyEventDtoToJSON)),
        'priceBreakdown': value['priceBreakdown'] == null ? undefined : ((value['priceBreakdown'] as Array<any>).map(PriceStepDtoToJSON)),
        'temperatureLogs': value['temperatureLogs'] == null ? undefined : ((value['temperatureLogs'] as Array<any>).map(TemperatureLogDtoToJSON)),
        'alerts': value['alerts'] == null ? undefined : ((value['alerts'] as Array<any>).map(AlertDtoToJSON)),
    };
}

