/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockDto
 */
export interface BlockDto {
    /**
     * 
     * @type {number}
     * @memberof BlockDto
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockDto
     */
    hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlockDto
     */
    previousHash?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BlockDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof BlockDto
     */
    step?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlockDto
     */
    location?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlockDto
     */
    carrier?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BlockDto
     */
    temperature?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BlockDto
     */
    isValid?: boolean;
}

/**
 * Check if a given object implements the BlockDto interface.
 */
export function instanceOfBlockDto(value: object): value is BlockDto {
    return true;
}

export function BlockDtoFromJSON(json: any): BlockDto {
    return BlockDtoFromJSONTyped(json, false);
}

export function BlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'previousHash': json['previousHash'] == null ? undefined : json['previousHash'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'step': json['step'] == null ? undefined : json['step'],
        'location': json['location'] == null ? undefined : json['location'],
        'carrier': json['carrier'] == null ? undefined : json['carrier'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
    };
}

export function BlockDtoToJSON(json: any): BlockDto {
    return BlockDtoToJSONTyped(json, false);
}

export function BlockDtoToJSONTyped(value?: BlockDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'hash': value['hash'],
        'previousHash': value['previousHash'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'step': value['step'],
        'location': value['location'],
        'carrier': value['carrier'],
        'temperature': value['temperature'],
        'isValid': value['isValid'],
    };
}

