/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockDto } from './BlockDto';
import {
    BlockDtoFromJSON,
    BlockDtoFromJSONTyped,
    BlockDtoToJSON,
    BlockDtoToJSONTyped,
} from './BlockDto';

/**
 * 
 * @export
 * @interface BlockchainDto
 */
export interface BlockchainDto {
    /**
     * 
     * @type {string}
     * @memberof BlockchainDto
     */
    batchId?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDto
     */
    lotNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlockchainDto
     */
    gtin?: string | null;
    /**
     * 
     * @type {Array<BlockDto>}
     * @memberof BlockchainDto
     */
    blocks?: Array<BlockDto> | null;
    /**
     * 
     * @type {boolean}
     * @memberof BlockchainDto
     */
    chainValid?: boolean;
}

/**
 * Check if a given object implements the BlockchainDto interface.
 */
export function instanceOfBlockchainDto(value: object): value is BlockchainDto {
    return true;
}

export function BlockchainDtoFromJSON(json: any): BlockchainDto {
    return BlockchainDtoFromJSONTyped(json, false);
}

export function BlockchainDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockchainDto {
    if (json == null) {
        return json;
    }
    return {
        
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'lotNumber': json['lotNumber'] == null ? undefined : json['lotNumber'],
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(BlockDtoFromJSON)),
        'chainValid': json['chainValid'] == null ? undefined : json['chainValid'],
    };
}

export function BlockchainDtoToJSON(json: any): BlockchainDto {
    return BlockchainDtoToJSONTyped(json, false);
}

export function BlockchainDtoToJSONTyped(value?: BlockchainDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batchId': value['batchId'],
        'lotNumber': value['lotNumber'],
        'gtin': value['gtin'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(BlockDtoToJSON)),
        'chainValid': value['chainValid'],
    };
}

