/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatResponseDto
 */
export interface ChatResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ChatResponseDto
     */
    answer?: string | null;
}

/**
 * Check if a given object implements the ChatResponseDto interface.
 */
export function instanceOfChatResponseDto(value: object): value is ChatResponseDto {
    return true;
}

export function ChatResponseDtoFromJSON(json: any): ChatResponseDto {
    return ChatResponseDtoFromJSONTyped(json, false);
}

export function ChatResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function ChatResponseDtoToJSON(json: any): ChatResponseDto {
    return ChatResponseDtoToJSONTyped(json, false);
}

export function ChatResponseDtoToJSONTyped(value?: ChatResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
    };
}

