/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageDto
 */
export interface ChatMessageDto {
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDto
     */
    role?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageDto
     */
    content?: string | null;
}

/**
 * Check if a given object implements the ChatMessageDto interface.
 */
export function instanceOfChatMessageDto(value: object): value is ChatMessageDto {
    return true;
}

export function ChatMessageDtoFromJSON(json: any): ChatMessageDto {
    return ChatMessageDtoFromJSONTyped(json, false);
}

export function ChatMessageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function ChatMessageDtoToJSON(json: any): ChatMessageDto {
    return ChatMessageDtoToJSONTyped(json, false);
}

export function ChatMessageDtoToJSONTyped(value?: ChatMessageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
    };
}

