/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Co2BreakdownItemDto
 */
export interface Co2BreakdownItemDto {
    /**
     * 
     * @type {string}
     * @memberof Co2BreakdownItemDto
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Co2BreakdownItemDto
     */
    stage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Co2BreakdownItemDto
     */
    co2Kg?: number;
    /**
     * 
     * @type {number}
     * @memberof Co2BreakdownItemDto
     */
    percentage?: number;
}

/**
 * Check if a given object implements the Co2BreakdownItemDto interface.
 */
export function instanceOfCo2BreakdownItemDto(value: object): value is Co2BreakdownItemDto {
    return true;
}

export function Co2BreakdownItemDtoFromJSON(json: any): Co2BreakdownItemDto {
    return Co2BreakdownItemDtoFromJSONTyped(json, false);
}

export function Co2BreakdownItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Co2BreakdownItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stage': json['stage'] == null ? undefined : json['stage'],
        'co2Kg': json['co2Kg'] == null ? undefined : json['co2Kg'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function Co2BreakdownItemDtoToJSON(json: any): Co2BreakdownItemDto {
    return Co2BreakdownItemDtoToJSONTyped(json, false);
}

export function Co2BreakdownItemDtoToJSONTyped(value?: Co2BreakdownItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stage': value['stage'],
        'co2Kg': value['co2Kg'],
        'percentage': value['percentage'],
    };
}

