/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColdChainAnomalyDto
 */
export interface ColdChainAnomalyDto {
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    severity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ColdChainAnomalyDto
     */
    minTemp?: number;
    /**
     * 
     * @type {number}
     * @memberof ColdChainAnomalyDto
     */
    maxTemp?: number;
    /**
     * 
     * @type {string}
     * @memberof ColdChainAnomalyDto
     */
    duration?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ColdChainAnomalyDto
     */
    affectedQualityPercent?: number;
}

/**
 * Check if a given object implements the ColdChainAnomalyDto interface.
 */
export function instanceOfColdChainAnomalyDto(value: object): value is ColdChainAnomalyDto {
    return true;
}

export function ColdChainAnomalyDtoFromJSON(json: any): ColdChainAnomalyDto {
    return ColdChainAnomalyDtoFromJSONTyped(json, false);
}

export function ColdChainAnomalyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColdChainAnomalyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'minTemp': json['minTemp'] == null ? undefined : json['minTemp'],
        'maxTemp': json['maxTemp'] == null ? undefined : json['maxTemp'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'affectedQualityPercent': json['affectedQualityPercent'] == null ? undefined : json['affectedQualityPercent'],
    };
}

export function ColdChainAnomalyDtoToJSON(json: any): ColdChainAnomalyDto {
    return ColdChainAnomalyDtoToJSONTyped(json, false);
}

export function ColdChainAnomalyDtoToJSONTyped(value?: ColdChainAnomalyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'severity': value['severity'],
        'type': value['type'],
        'title': value['title'],
        'description': value['description'],
        'minTemp': value['minTemp'],
        'maxTemp': value['maxTemp'],
        'duration': value['duration'],
        'affectedQualityPercent': value['affectedQualityPercent'],
    };
}

