/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinateDto
 */
export interface CoordinateDto {
    /**
     * 
     * @type {string}
     * @memberof CoordinateDto
     */
    step?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CoordinateDto
     */
    location?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CoordinateDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinateDto
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof CoordinateDto
     */
    status?: number;
}

/**
 * Check if a given object implements the CoordinateDto interface.
 */
export function instanceOfCoordinateDto(value: object): value is CoordinateDto {
    return true;
}

export function CoordinateDtoFromJSON(json: any): CoordinateDto {
    return CoordinateDtoFromJSONTyped(json, false);
}

export function CoordinateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'step': json['step'] == null ? undefined : json['step'],
        'location': json['location'] == null ? undefined : json['location'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CoordinateDtoToJSON(json: any): CoordinateDto {
    return CoordinateDtoToJSONTyped(json, false);
}

export function CoordinateDtoToJSONTyped(value?: CoordinateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'step': value['step'],
        'location': value['location'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'status': value['status'],
    };
}

