/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExampleCommand
 */
export interface CreateExampleCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateExampleCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateExampleCommand
     */
    description?: string | null;
}

/**
 * Check if a given object implements the CreateExampleCommand interface.
 */
export function instanceOfCreateExampleCommand(value: object): value is CreateExampleCommand {
    return true;
}

export function CreateExampleCommandFromJSON(json: any): CreateExampleCommand {
    return CreateExampleCommandFromJSONTyped(json, false);
}

export function CreateExampleCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExampleCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function CreateExampleCommandToJSON(json: any): CreateExampleCommand {
    return CreateExampleCommandToJSONTyped(json, false);
}

export function CreateExampleCommandToJSONTyped(value?: CreateExampleCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
    };
}

