/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReportDto
 */
export interface CreateReportDto {
    /**
     * 
     * @type {string}
     * @memberof CreateReportDto
     */
    reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReportDto
     */
    details?: string | null;
}

/**
 * Check if a given object implements the CreateReportDto interface.
 */
export function instanceOfCreateReportDto(value: object): value is CreateReportDto {
    return true;
}

export function CreateReportDtoFromJSON(json: any): CreateReportDto {
    return CreateReportDtoFromJSONTyped(json, false);
}

export function CreateReportDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function CreateReportDtoToJSON(json: any): CreateReportDto {
    return CreateReportDtoToJSONTyped(json, false);
}

export function CreateReportDtoToJSONTyped(value?: CreateReportDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
        'details': value['details'],
    };
}

