/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JourneyStatus } from './JourneyStatus';
import {
    JourneyStatusFromJSON,
    JourneyStatusFromJSONTyped,
    JourneyStatusToJSON,
    JourneyStatusToJSONTyped,
} from './JourneyStatus';

/**
 * 
 * @export
 * @interface JourneyEventDto
 */
export interface JourneyEventDto {
    /**
     * 
     * @type {string}
     * @memberof JourneyEventDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JourneyEventDto
     */
    step?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JourneyEventDto
     */
    location?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    longitude?: number;
    /**
     * 
     * @type {Date}
     * @memberof JourneyEventDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {JourneyStatus}
     * @memberof JourneyEventDto
     */
    status?: JourneyStatus;
    /**
     * 
     * @type {string}
     * @memberof JourneyEventDto
     */
    icon?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    temperature?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JourneyEventDto
     */
    details?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    co2Kg?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    waterLiters?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JourneyEventDto
     */
    cost?: number | null;
}



/**
 * Check if a given object implements the JourneyEventDto interface.
 */
export function instanceOfJourneyEventDto(value: object): value is JourneyEventDto {
    return true;
}

export function JourneyEventDtoFromJSON(json: any): JourneyEventDto {
    return JourneyEventDtoFromJSONTyped(json, false);
}

export function JourneyEventDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyEventDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'step': json['step'] == null ? undefined : json['step'],
        'location': json['location'] == null ? undefined : json['location'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'status': json['status'] == null ? undefined : JourneyStatusFromJSON(json['status']),
        'icon': json['icon'] == null ? undefined : json['icon'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'details': json['details'] == null ? undefined : json['details'],
        'co2Kg': json['co2Kg'] == null ? undefined : json['co2Kg'],
        'waterLiters': json['waterLiters'] == null ? undefined : json['waterLiters'],
        'cost': json['cost'] == null ? undefined : json['cost'],
    };
}

export function JourneyEventDtoToJSON(json: any): JourneyEventDto {
    return JourneyEventDtoToJSONTyped(json, false);
}

export function JourneyEventDtoToJSONTyped(value?: JourneyEventDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'step': value['step'],
        'location': value['location'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'status': JourneyStatusToJSON(value['status']),
        'icon': value['icon'],
        'temperature': value['temperature'],
        'details': value['details'],
        'co2Kg': value['co2Kg'],
        'waterLiters': value['waterLiters'],
        'cost': value['cost'],
    };
}

