/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinateDto } from './CoordinateDto';
import {
    CoordinateDtoFromJSON,
    CoordinateDtoFromJSONTyped,
    CoordinateDtoToJSON,
    CoordinateDtoToJSONTyped,
} from './CoordinateDto';

/**
 * 
 * @export
 * @interface JourneyCoordinatesDto
 */
export interface JourneyCoordinatesDto {
    /**
     * 
     * @type {string}
     * @memberof JourneyCoordinatesDto
     */
    productId?: string;
    /**
     * 
     * @type {Array<CoordinateDto>}
     * @memberof JourneyCoordinatesDto
     */
    coordinates?: Array<CoordinateDto> | null;
}

/**
 * Check if a given object implements the JourneyCoordinatesDto interface.
 */
export function instanceOfJourneyCoordinatesDto(value: object): value is JourneyCoordinatesDto {
    return true;
}

export function JourneyCoordinatesDtoFromJSON(json: any): JourneyCoordinatesDto {
    return JourneyCoordinatesDtoFromJSONTyped(json, false);
}

export function JourneyCoordinatesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyCoordinatesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'coordinates': json['coordinates'] == null ? undefined : ((json['coordinates'] as Array<any>).map(CoordinateDtoFromJSON)),
    };
}

export function JourneyCoordinatesDtoToJSON(json: any): JourneyCoordinatesDto {
    return JourneyCoordinatesDtoToJSONTyped(json, false);
}

export function JourneyCoordinatesDtoToJSONTyped(value?: JourneyCoordinatesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'coordinates': value['coordinates'] == null ? undefined : ((value['coordinates'] as Array<any>).map(CoordinateDtoToJSON)),
    };
}

