/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JourneyStatus = {
    Completed: 'Completed',
    Current: 'Current',
    Warning: 'Warning'
} as const;
export type JourneyStatus = typeof JourneyStatus[keyof typeof JourneyStatus];


export function instanceOfJourneyStatus(value: any): boolean {
    for (const key in JourneyStatus) {
        if (Object.prototype.hasOwnProperty.call(JourneyStatus, key)) {
            if (JourneyStatus[key as keyof typeof JourneyStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JourneyStatusFromJSON(json: any): JourneyStatus {
    return JourneyStatusFromJSONTyped(json, false);
}

export function JourneyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): JourneyStatus {
    return json as JourneyStatus;
}

export function JourneyStatusToJSON(value?: JourneyStatus | null): any {
    return value as any;
}

export function JourneyStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): JourneyStatus {
    return value as JourneyStatus;
}

