/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NutritionDto
 */
export interface NutritionDto {
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    energyKcal?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    fat?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    saturatedFat?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    carbs?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    sugars?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    fiber?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    protein?: number;
    /**
     * 
     * @type {number}
     * @memberof NutritionDto
     */
    salt?: number;
}

/**
 * Check if a given object implements the NutritionDto interface.
 */
export function instanceOfNutritionDto(value: object): value is NutritionDto {
    return true;
}

export function NutritionDtoFromJSON(json: any): NutritionDto {
    return NutritionDtoFromJSONTyped(json, false);
}

export function NutritionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NutritionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'energyKcal': json['energyKcal'] == null ? undefined : json['energyKcal'],
        'fat': json['fat'] == null ? undefined : json['fat'],
        'saturatedFat': json['saturatedFat'] == null ? undefined : json['saturatedFat'],
        'carbs': json['carbs'] == null ? undefined : json['carbs'],
        'sugars': json['sugars'] == null ? undefined : json['sugars'],
        'fiber': json['fiber'] == null ? undefined : json['fiber'],
        'protein': json['protein'] == null ? undefined : json['protein'],
        'salt': json['salt'] == null ? undefined : json['salt'],
    };
}

export function NutritionDtoToJSON(json: any): NutritionDto {
    return NutritionDtoToJSONTyped(json, false);
}

export function NutritionDtoToJSONTyped(value?: NutritionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'energyKcal': value['energyKcal'],
        'fat': value['fat'],
        'saturatedFat': value['saturatedFat'],
        'carbs': value['carbs'],
        'sugars': value['sugars'],
        'fiber': value['fiber'],
        'protein': value['protein'],
        'salt': value['salt'],
    };
}

