/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OcrResultDto
 */
export interface OcrResultDto {
    /**
     * 
     * @type {string}
     * @memberof OcrResultDto
     */
    lotNumber?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OcrResultDto
     */
    success?: boolean;
}

/**
 * Check if a given object implements the OcrResultDto interface.
 */
export function instanceOfOcrResultDto(value: object): value is OcrResultDto {
    return true;
}

export function OcrResultDtoFromJSON(json: any): OcrResultDto {
    return OcrResultDtoFromJSONTyped(json, false);
}

export function OcrResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OcrResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lotNumber': json['lotNumber'] == null ? undefined : json['lotNumber'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function OcrResultDtoToJSON(json: any): OcrResultDto {
    return OcrResultDtoToJSONTyped(json, false);
}

export function OcrResultDtoToJSONTyped(value?: OcrResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lotNumber': value['lotNumber'],
        'success': value['success'],
    };
}

