/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PointToPointRouteDto
 */
export interface PointToPointRouteDto {
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof PointToPointRouteDto
     */
    points?: Array<Array<number>> | null;
}

/**
 * Check if a given object implements the PointToPointRouteDto interface.
 */
export function instanceOfPointToPointRouteDto(value: object): value is PointToPointRouteDto {
    return true;
}

export function PointToPointRouteDtoFromJSON(json: any): PointToPointRouteDto {
    return PointToPointRouteDtoFromJSONTyped(json, false);
}

export function PointToPointRouteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointToPointRouteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'points': json['points'] == null ? undefined : json['points'],
    };
}

export function PointToPointRouteDtoToJSON(json: any): PointToPointRouteDto {
    return PointToPointRouteDtoToJSONTyped(json, false);
}

export function PointToPointRouteDtoToJSONTyped(value?: PointToPointRouteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'points': value['points'],
    };
}

