/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceStepDto
 */
export interface PriceStepDto {
    /**
     * 
     * @type {string}
     * @memberof PriceStepDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceStepDto
     */
    stage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PriceStepDto
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof PriceStepDto
     */
    percentage?: number;
}

/**
 * Check if a given object implements the PriceStepDto interface.
 */
export function instanceOfPriceStepDto(value: object): value is PriceStepDto {
    return true;
}

export function PriceStepDtoFromJSON(json: any): PriceStepDto {
    return PriceStepDtoFromJSONTyped(json, false);
}

export function PriceStepDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceStepDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stage': json['stage'] == null ? undefined : json['stage'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function PriceStepDtoToJSON(json: any): PriceStepDto {
    return PriceStepDtoToJSONTyped(json, false);
}

export function PriceStepDtoToJSONTyped(value?: PriceStepDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stage': value['stage'],
        'amount': value['amount'],
        'percentage': value['percentage'],
    };
}

