/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlternativeProductDto } from './AlternativeProductDto';
import {
    AlternativeProductDtoFromJSON,
    AlternativeProductDtoFromJSONTyped,
    AlternativeProductDtoToJSON,
    AlternativeProductDtoToJSONTyped,
} from './AlternativeProductDto';

/**
 * 
 * @export
 * @interface ProductAlternativesDto
 */
export interface ProductAlternativesDto {
    /**
     * 
     * @type {Array<AlternativeProductDto>}
     * @memberof ProductAlternativesDto
     */
    alternatives?: Array<AlternativeProductDto> | null;
}

/**
 * Check if a given object implements the ProductAlternativesDto interface.
 */
export function instanceOfProductAlternativesDto(value: object): value is ProductAlternativesDto {
    return true;
}

export function ProductAlternativesDtoFromJSON(json: any): ProductAlternativesDto {
    return ProductAlternativesDtoFromJSONTyped(json, false);
}

export function ProductAlternativesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAlternativesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'alternatives': json['alternatives'] == null ? undefined : ((json['alternatives'] as Array<any>).map(AlternativeProductDtoFromJSON)),
    };
}

export function ProductAlternativesDtoToJSON(json: any): ProductAlternativesDto {
    return ProductAlternativesDtoToJSONTyped(json, false);
}

export function ProductAlternativesDtoToJSONTyped(value?: ProductAlternativesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alternatives': value['alternatives'] == null ? undefined : ((value['alternatives'] as Array<any>).map(AlternativeProductDtoToJSON)),
    };
}

