/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProductStatus = {
    Ok: 'Ok',
    Warning: 'Warning',
    Recall: 'Recall'
} as const;
export type ProductStatus = typeof ProductStatus[keyof typeof ProductStatus];


export function instanceOfProductStatus(value: any): boolean {
    for (const key in ProductStatus) {
        if (Object.prototype.hasOwnProperty.call(ProductStatus, key)) {
            if (ProductStatus[key as keyof typeof ProductStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProductStatusFromJSON(json: any): ProductStatus {
    return ProductStatusFromJSONTyped(json, false);
}

export function ProductStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductStatus {
    return json as ProductStatus;
}

export function ProductStatusToJSON(value?: ProductStatus | null): any {
    return value as any;
}

export function ProductStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ProductStatus {
    return value as ProductStatus;
}

