/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchSummaryDto } from './BatchSummaryDto';
import {
    BatchSummaryDtoFromJSON,
    BatchSummaryDtoFromJSONTyped,
    BatchSummaryDtoToJSON,
    BatchSummaryDtoToJSONTyped,
} from './BatchSummaryDto';
import type { NutritionDto } from './NutritionDto';
import {
    NutritionDtoFromJSON,
    NutritionDtoFromJSONTyped,
    NutritionDtoToJSON,
    NutritionDtoToJSONTyped,
} from './NutritionDto';

/**
 * 
 * @export
 * @interface ProductDto
 */
export interface ProductDto {
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    gtin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    weight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    origin?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductDto
     */
    certifications?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    nutriScore?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    novaGroup?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    ecoScore?: string | null;
    /**
     * 
     * @type {NutritionDto}
     * @memberof ProductDto
     */
    nutrition?: NutritionDto;
    /**
     * 
     * @type {Array<BatchSummaryDto>}
     * @memberof ProductDto
     */
    batches?: Array<BatchSummaryDto> | null;
}

/**
 * Check if a given object implements the ProductDto interface.
 */
export function instanceOfProductDto(value: object): value is ProductDto {
    return true;
}

export function ProductDtoFromJSON(json: any): ProductDto {
    return ProductDtoFromJSONTyped(json, false);
}

export function ProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'name': json['name'] == null ? undefined : json['name'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'category': json['category'] == null ? undefined : json['category'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'certifications': json['certifications'] == null ? undefined : json['certifications'],
        'nutriScore': json['nutriScore'] == null ? undefined : json['nutriScore'],
        'novaGroup': json['novaGroup'] == null ? undefined : json['novaGroup'],
        'ecoScore': json['ecoScore'] == null ? undefined : json['ecoScore'],
        'nutrition': json['nutrition'] == null ? undefined : NutritionDtoFromJSON(json['nutrition']),
        'batches': json['batches'] == null ? undefined : ((json['batches'] as Array<any>).map(BatchSummaryDtoFromJSON)),
    };
}

export function ProductDtoToJSON(json: any): ProductDto {
    return ProductDtoToJSONTyped(json, false);
}

export function ProductDtoToJSONTyped(value?: ProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'gtin': value['gtin'],
        'name': value['name'],
        'brand': value['brand'],
        'imageUrl': value['imageUrl'],
        'category': value['category'],
        'weight': value['weight'],
        'origin': value['origin'],
        'certifications': value['certifications'],
        'nutriScore': value['nutriScore'],
        'novaGroup': value['novaGroup'],
        'ecoScore': value['ecoScore'],
        'nutrition': NutritionDtoToJSON(value['nutrition']),
        'batches': value['batches'] == null ? undefined : ((value['batches'] as Array<any>).map(BatchSummaryDtoToJSON)),
    };
}

