/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductSummaryDto
 */
export interface ProductSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    gtin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductSummaryDto
     */
    nutriScore?: string | null;
}

/**
 * Check if a given object implements the ProductSummaryDto interface.
 */
export function instanceOfProductSummaryDto(value: object): value is ProductSummaryDto {
    return true;
}

export function ProductSummaryDtoFromJSON(json: any): ProductSummaryDto {
    return ProductSummaryDtoFromJSONTyped(json, false);
}

export function ProductSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'name': json['name'] == null ? undefined : json['name'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'category': json['category'] == null ? undefined : json['category'],
        'nutriScore': json['nutriScore'] == null ? undefined : json['nutriScore'],
    };
}

export function ProductSummaryDtoToJSON(json: any): ProductSummaryDto {
    return ProductSummaryDtoToJSONTyped(json, false);
}

export function ProductSummaryDtoToJSONTyped(value?: ProductSummaryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'gtin': value['gtin'],
        'name': value['name'],
        'brand': value['brand'],
        'imageUrl': value['imageUrl'],
        'category': value['category'],
        'nutriScore': value['nutriScore'],
    };
}

