/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductReportDto
 */
export interface ProductReportDto {
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    productName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    productBrand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    productImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    batchId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    reason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductReportDto
     */
    details?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductReportDto
     */
    resolved?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductReportDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the ProductReportDto interface.
 */
export function instanceOfProductReportDto(value: object): value is ProductReportDto {
    return true;
}

export function ProductReportDtoFromJSON(json: any): ProductReportDto {
    return ProductReportDtoFromJSONTyped(json, false);
}

export function ProductReportDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductReportDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'productBrand': json['productBrand'] == null ? undefined : json['productBrand'],
        'productImageUrl': json['productImageUrl'] == null ? undefined : json['productImageUrl'],
        'batchId': json['batchId'] == null ? undefined : json['batchId'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'details': json['details'] == null ? undefined : json['details'],
        'resolved': json['resolved'] == null ? undefined : json['resolved'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ProductReportDtoToJSON(json: any): ProductReportDto {
    return ProductReportDtoToJSONTyped(json, false);
}

export function ProductReportDtoToJSONTyped(value?: ProductReportDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'productId': value['productId'],
        'productName': value['productName'],
        'productBrand': value['productBrand'],
        'productImageUrl': value['productImageUrl'],
        'batchId': value['batchId'],
        'reason': value['reason'],
        'details': value['details'],
        'resolved': value['resolved'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

