/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlertDto } from './AlertDto';
import {
    AlertDtoFromJSON,
    AlertDtoFromJSONTyped,
    AlertDtoToJSON,
    AlertDtoToJSONTyped,
} from './AlertDto';
import type { NutritionDto } from './NutritionDto';
import {
    NutritionDtoFromJSON,
    NutritionDtoFromJSONTyped,
    NutritionDtoToJSON,
    NutritionDtoToJSONTyped,
} from './NutritionDto';
import type { TemperatureLogDto } from './TemperatureLogDto';
import {
    TemperatureLogDtoFromJSON,
    TemperatureLogDtoFromJSONTyped,
    TemperatureLogDtoToJSON,
    TemperatureLogDtoToJSONTyped,
} from './TemperatureLogDto';
import type { PriceStepDto } from './PriceStepDto';
import {
    PriceStepDtoFromJSON,
    PriceStepDtoFromJSONTyped,
    PriceStepDtoToJSON,
    PriceStepDtoToJSONTyped,
} from './PriceStepDto';
import type { ProductStatus } from './ProductStatus';
import {
    ProductStatusFromJSON,
    ProductStatusFromJSONTyped,
    ProductStatusToJSON,
    ProductStatusToJSONTyped,
} from './ProductStatus';
import type { JourneyEventDto } from './JourneyEventDto';
import {
    JourneyEventDtoFromJSON,
    JourneyEventDtoFromJSONTyped,
    JourneyEventDtoToJSON,
    JourneyEventDtoToJSONTyped,
} from './JourneyEventDto';

/**
 * 
 * @export
 * @interface ProductDto
 */
export interface ProductDto {
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    gtin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    weight?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    origin?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductDto
     */
    certifications?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    nutriScore?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    novaGroup?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductDto
     */
    ecoScore?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    riskScore?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    shelfLifeDays?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    daysRemaining?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    co2Kg?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductDto
     */
    waterLiters?: number | null;
    /**
     * 
     * @type {ProductStatus}
     * @memberof ProductDto
     */
    status?: ProductStatus;
    /**
     * 
     * @type {NutritionDto}
     * @memberof ProductDto
     */
    nutrition?: NutritionDto;
    /**
     * 
     * @type {Array<JourneyEventDto>}
     * @memberof ProductDto
     */
    journeyEvents?: Array<JourneyEventDto> | null;
    /**
     * 
     * @type {Array<PriceStepDto>}
     * @memberof ProductDto
     */
    priceBreakdown?: Array<PriceStepDto> | null;
    /**
     * 
     * @type {Array<TemperatureLogDto>}
     * @memberof ProductDto
     */
    temperatureLogs?: Array<TemperatureLogDto> | null;
    /**
     * 
     * @type {Array<AlertDto>}
     * @memberof ProductDto
     */
    alerts?: Array<AlertDto> | null;
}



/**
 * Check if a given object implements the ProductDto interface.
 */
export function instanceOfProductDto(value: object): value is ProductDto {
    return true;
}

export function ProductDtoFromJSON(json: any): ProductDto {
    return ProductDtoFromJSONTyped(json, false);
}

export function ProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'gtin': json['gtin'] == null ? undefined : json['gtin'],
        'name': json['name'] == null ? undefined : json['name'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'category': json['category'] == null ? undefined : json['category'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'certifications': json['certifications'] == null ? undefined : json['certifications'],
        'nutriScore': json['nutriScore'] == null ? undefined : json['nutriScore'],
        'novaGroup': json['novaGroup'] == null ? undefined : json['novaGroup'],
        'ecoScore': json['ecoScore'] == null ? undefined : json['ecoScore'],
        'riskScore': json['riskScore'] == null ? undefined : json['riskScore'],
        'shelfLifeDays': json['shelfLifeDays'] == null ? undefined : json['shelfLifeDays'],
        'daysRemaining': json['daysRemaining'] == null ? undefined : json['daysRemaining'],
        'co2Kg': json['co2Kg'] == null ? undefined : json['co2Kg'],
        'waterLiters': json['waterLiters'] == null ? undefined : json['waterLiters'],
        'status': json['status'] == null ? undefined : ProductStatusFromJSON(json['status']),
        'nutrition': json['nutrition'] == null ? undefined : NutritionDtoFromJSON(json['nutrition']),
        'journeyEvents': json['journeyEvents'] == null ? undefined : ((json['journeyEvents'] as Array<any>).map(JourneyEventDtoFromJSON)),
        'priceBreakdown': json['priceBreakdown'] == null ? undefined : ((json['priceBreakdown'] as Array<any>).map(PriceStepDtoFromJSON)),
        'temperatureLogs': json['temperatureLogs'] == null ? undefined : ((json['temperatureLogs'] as Array<any>).map(TemperatureLogDtoFromJSON)),
        'alerts': json['alerts'] == null ? undefined : ((json['alerts'] as Array<any>).map(AlertDtoFromJSON)),
    };
}

export function ProductDtoToJSON(json: any): ProductDto {
    return ProductDtoToJSONTyped(json, false);
}

export function ProductDtoToJSONTyped(value?: ProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'gtin': value['gtin'],
        'name': value['name'],
        'brand': value['brand'],
        'imageUrl': value['imageUrl'],
        'category': value['category'],
        'weight': value['weight'],
        'origin': value['origin'],
        'certifications': value['certifications'],
        'nutriScore': value['nutriScore'],
        'novaGroup': value['novaGroup'],
        'ecoScore': value['ecoScore'],
        'riskScore': value['riskScore'],
        'shelfLifeDays': value['shelfLifeDays'],
        'daysRemaining': value['daysRemaining'],
        'co2Kg': value['co2Kg'],
        'waterLiters': value['waterLiters'],
        'status': ProductStatusToJSON(value['status']),
        'nutrition': NutritionDtoToJSON(value['nutrition']),
        'journeyEvents': value['journeyEvents'] == null ? undefined : ((value['journeyEvents'] as Array<any>).map(JourneyEventDtoToJSON)),
        'priceBreakdown': value['priceBreakdown'] == null ? undefined : ((value['priceBreakdown'] as Array<any>).map(PriceStepDtoToJSON)),
        'temperatureLogs': value['temperatureLogs'] == null ? undefined : ((value['temperatureLogs'] as Array<any>).map(TemperatureLogDtoToJSON)),
        'alerts': value['alerts'] == null ? undefined : ((value['alerts'] as Array<any>).map(AlertDtoToJSON)),
    };
}

