/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QualityDataPointDto
 */
export interface QualityDataPointDto {
    /**
     * 
     * @type {number}
     * @memberof QualityDataPointDto
     */
    day?: number;
    /**
     * 
     * @type {number}
     * @memberof QualityDataPointDto
     */
    quality?: number;
    /**
     * 
     * @type {string}
     * @memberof QualityDataPointDto
     */
    label?: string | null;
}

/**
 * Check if a given object implements the QualityDataPointDto interface.
 */
export function instanceOfQualityDataPointDto(value: object): value is QualityDataPointDto {
    return true;
}

export function QualityDataPointDtoFromJSON(json: any): QualityDataPointDto {
    return QualityDataPointDtoFromJSONTyped(json, false);
}

export function QualityDataPointDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QualityDataPointDto {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'quality': json['quality'] == null ? undefined : json['quality'],
        'label': json['label'] == null ? undefined : json['label'],
    };
}

export function QualityDataPointDtoToJSON(json: any): QualityDataPointDto {
    return QualityDataPointDtoToJSONTyped(json, false);
}

export function QualityDataPointDtoToJSONTyped(value?: QualityDataPointDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'quality': value['quality'],
        'label': value['label'],
    };
}

