/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskFactorDto
 */
export interface RiskFactorDto {
    /**
     * 
     * @type {string}
     * @memberof RiskFactorDto
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RiskFactorDto
     */
    factor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RiskFactorDto
     */
    impact?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RiskFactorDto
     */
    description?: string | null;
}

/**
 * Check if a given object implements the RiskFactorDto interface.
 */
export function instanceOfRiskFactorDto(value: object): value is RiskFactorDto {
    return true;
}

export function RiskFactorDtoFromJSON(json: any): RiskFactorDto {
    return RiskFactorDtoFromJSONTyped(json, false);
}

export function RiskFactorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskFactorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'factor': json['factor'] == null ? undefined : json['factor'],
        'impact': json['impact'] == null ? undefined : json['impact'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function RiskFactorDtoToJSON(json: any): RiskFactorDto {
    return RiskFactorDtoToJSONTyped(json, false);
}

export function RiskFactorDtoToJSONTyped(value?: RiskFactorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'factor': value['factor'],
        'impact': value['impact'],
        'description': value['description'],
    };
}

