/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteSegmentDto
 */
export interface RouteSegmentDto {
    /**
     * 
     * @type {string}
     * @memberof RouteSegmentDto
     */
    fromStep?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteSegmentDto
     */
    toStep?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteSegmentDto
     */
    fromLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteSegmentDto
     */
    toLocation?: string | null;
    /**
     * 
     * @type {Array<Array<number>>}
     * @memberof RouteSegmentDto
     */
    points?: Array<Array<number>> | null;
}

/**
 * Check if a given object implements the RouteSegmentDto interface.
 */
export function instanceOfRouteSegmentDto(value: object): value is RouteSegmentDto {
    return true;
}

export function RouteSegmentDtoFromJSON(json: any): RouteSegmentDto {
    return RouteSegmentDtoFromJSONTyped(json, false);
}

export function RouteSegmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteSegmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fromStep': json['fromStep'] == null ? undefined : json['fromStep'],
        'toStep': json['toStep'] == null ? undefined : json['toStep'],
        'fromLocation': json['fromLocation'] == null ? undefined : json['fromLocation'],
        'toLocation': json['toLocation'] == null ? undefined : json['toLocation'],
        'points': json['points'] == null ? undefined : json['points'],
    };
}

export function RouteSegmentDtoToJSON(json: any): RouteSegmentDto {
    return RouteSegmentDtoToJSONTyped(json, false);
}

export function RouteSegmentDtoToJSONTyped(value?: RouteSegmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromStep': value['fromStep'],
        'toStep': value['toStep'],
        'fromLocation': value['fromLocation'],
        'toLocation': value['toLocation'],
        'points': value['points'],
    };
}

