/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RouteSegmentDto } from './RouteSegmentDto';
import {
    RouteSegmentDtoFromJSON,
    RouteSegmentDtoFromJSONTyped,
    RouteSegmentDtoToJSON,
    RouteSegmentDtoToJSONTyped,
} from './RouteSegmentDto';

/**
 * 
 * @export
 * @interface RouteDto
 */
export interface RouteDto {
    /**
     * 
     * @type {Array<RouteSegmentDto>}
     * @memberof RouteDto
     */
    segments?: Array<RouteSegmentDto> | null;
}

/**
 * Check if a given object implements the RouteDto interface.
 */
export function instanceOfRouteDto(value: object): value is RouteDto {
    return true;
}

export function RouteDtoFromJSON(json: any): RouteDto {
    return RouteDtoFromJSONTyped(json, false);
}

export function RouteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'segments': json['segments'] == null ? undefined : ((json['segments'] as Array<any>).map(RouteSegmentDtoFromJSON)),
    };
}

export function RouteDtoToJSON(json: any): RouteDto {
    return RouteDtoToJSONTyped(json, false);
}

export function RouteDtoToJSONTyped(value?: RouteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'segments': value['segments'] == null ? undefined : ((value['segments'] as Array<any>).map(RouteSegmentDtoToJSON)),
    };
}

