/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductStatus } from './ProductStatus';
import {
    ProductStatusFromJSON,
    ProductStatusFromJSONTyped,
    ProductStatusToJSON,
    ProductStatusToJSONTyped,
} from './ProductStatus';

/**
 * 
 * @export
 * @interface ScanRecordDto
 */
export interface ScanRecordDto {
    /**
     * 
     * @type {string}
     * @memberof ScanRecordDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ScanRecordDto
     */
    productId?: string;
    /**
     * 
     * @type {string}
     * @memberof ScanRecordDto
     */
    productName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanRecordDto
     */
    productBrand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScanRecordDto
     */
    productImageUrl?: string | null;
    /**
     * 
     * @type {ProductStatus}
     * @memberof ScanRecordDto
     */
    productStatus?: ProductStatus;
    /**
     * 
     * @type {Date}
     * @memberof ScanRecordDto
     */
    scannedAt?: Date;
}



/**
 * Check if a given object implements the ScanRecordDto interface.
 */
export function instanceOfScanRecordDto(value: object): value is ScanRecordDto {
    return true;
}

export function ScanRecordDtoFromJSON(json: any): ScanRecordDto {
    return ScanRecordDtoFromJSONTyped(json, false);
}

export function ScanRecordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanRecordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'productBrand': json['productBrand'] == null ? undefined : json['productBrand'],
        'productImageUrl': json['productImageUrl'] == null ? undefined : json['productImageUrl'],
        'productStatus': json['productStatus'] == null ? undefined : ProductStatusFromJSON(json['productStatus']),
        'scannedAt': json['scannedAt'] == null ? undefined : (new Date(json['scannedAt'])),
    };
}

export function ScanRecordDtoToJSON(json: any): ScanRecordDto {
    return ScanRecordDtoToJSONTyped(json, false);
}

export function ScanRecordDtoToJSONTyped(value?: ScanRecordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'productId': value['productId'],
        'productName': value['productName'],
        'productBrand': value['productBrand'],
        'productImageUrl': value['productImageUrl'],
        'productStatus': ProductStatusToJSON(value['productStatus']),
        'scannedAt': value['scannedAt'] == null ? undefined : ((value['scannedAt']).toISOString()),
    };
}

