/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskFactorDto } from './RiskFactorDto';
import {
    RiskFactorDtoFromJSON,
    RiskFactorDtoFromJSONTyped,
    RiskFactorDtoToJSON,
    RiskFactorDtoToJSONTyped,
} from './RiskFactorDto';
import type { QualityDataPointDto } from './QualityDataPointDto';
import {
    QualityDataPointDtoFromJSON,
    QualityDataPointDtoFromJSONTyped,
    QualityDataPointDtoToJSON,
    QualityDataPointDtoToJSONTyped,
} from './QualityDataPointDto';

/**
 * 
 * @export
 * @interface ShelfLifePredictionDto
 */
export interface ShelfLifePredictionDto {
    /**
     * 
     * @type {number}
     * @memberof ShelfLifePredictionDto
     */
    predictedDaysRemaining?: number;
    /**
     * 
     * @type {number}
     * @memberof ShelfLifePredictionDto
     */
    confidence?: number;
    /**
     * 
     * @type {Array<QualityDataPointDto>}
     * @memberof ShelfLifePredictionDto
     */
    qualityProgression?: Array<QualityDataPointDto> | null;
    /**
     * 
     * @type {Array<RiskFactorDto>}
     * @memberof ShelfLifePredictionDto
     */
    riskFactors?: Array<RiskFactorDto> | null;
    /**
     * 
     * @type {string}
     * @memberof ShelfLifePredictionDto
     */
    recommendation?: string | null;
}

/**
 * Check if a given object implements the ShelfLifePredictionDto interface.
 */
export function instanceOfShelfLifePredictionDto(value: object): value is ShelfLifePredictionDto {
    return true;
}

export function ShelfLifePredictionDtoFromJSON(json: any): ShelfLifePredictionDto {
    return ShelfLifePredictionDtoFromJSONTyped(json, false);
}

export function ShelfLifePredictionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShelfLifePredictionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'predictedDaysRemaining': json['predictedDaysRemaining'] == null ? undefined : json['predictedDaysRemaining'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'qualityProgression': json['qualityProgression'] == null ? undefined : ((json['qualityProgression'] as Array<any>).map(QualityDataPointDtoFromJSON)),
        'riskFactors': json['riskFactors'] == null ? undefined : ((json['riskFactors'] as Array<any>).map(RiskFactorDtoFromJSON)),
        'recommendation': json['recommendation'] == null ? undefined : json['recommendation'],
    };
}

export function ShelfLifePredictionDtoToJSON(json: any): ShelfLifePredictionDto {
    return ShelfLifePredictionDtoToJSONTyped(json, false);
}

export function ShelfLifePredictionDtoToJSONTyped(value?: ShelfLifePredictionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'predictedDaysRemaining': value['predictedDaysRemaining'],
        'confidence': value['confidence'],
        'qualityProgression': value['qualityProgression'] == null ? undefined : ((value['qualityProgression'] as Array<any>).map(QualityDataPointDtoToJSON)),
        'riskFactors': value['riskFactors'] == null ? undefined : ((value['riskFactors'] as Array<any>).map(RiskFactorDtoToJSON)),
        'recommendation': value['recommendation'],
    };
}

