/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Co2BreakdownItemDto } from './Co2BreakdownItemDto';
import {
    Co2BreakdownItemDtoFromJSON,
    Co2BreakdownItemDtoFromJSONTyped,
    Co2BreakdownItemDtoToJSON,
    Co2BreakdownItemDtoToJSONTyped,
} from './Co2BreakdownItemDto';

/**
 * 
 * @export
 * @interface SustainabilityAnalysisDto
 */
export interface SustainabilityAnalysisDto {
    /**
     * 
     * @type {Array<Co2BreakdownItemDto>}
     * @memberof SustainabilityAnalysisDto
     */
    co2Breakdown?: Array<Co2BreakdownItemDto> | null;
    /**
     * 
     * @type {number}
     * @memberof SustainabilityAnalysisDto
     */
    totalCo2Kg?: number;
    /**
     * 
     * @type {number}
     * @memberof SustainabilityAnalysisDto
     */
    comparisonToAverage?: number;
    /**
     * 
     * @type {number}
     * @memberof SustainabilityAnalysisDto
     */
    waterFootprintL?: number;
    /**
     * 
     * @type {number}
     * @memberof SustainabilityAnalysisDto
     */
    transportDistanceKm?: number;
    /**
     * 
     * @type {string}
     * @memberof SustainabilityAnalysisDto
     */
    packagingScore?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SustainabilityAnalysisDto
     */
    ecoTips?: Array<string> | null;
}

/**
 * Check if a given object implements the SustainabilityAnalysisDto interface.
 */
export function instanceOfSustainabilityAnalysisDto(value: object): value is SustainabilityAnalysisDto {
    return true;
}

export function SustainabilityAnalysisDtoFromJSON(json: any): SustainabilityAnalysisDto {
    return SustainabilityAnalysisDtoFromJSONTyped(json, false);
}

export function SustainabilityAnalysisDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SustainabilityAnalysisDto {
    if (json == null) {
        return json;
    }
    return {
        
        'co2Breakdown': json['co2Breakdown'] == null ? undefined : ((json['co2Breakdown'] as Array<any>).map(Co2BreakdownItemDtoFromJSON)),
        'totalCo2Kg': json['totalCo2Kg'] == null ? undefined : json['totalCo2Kg'],
        'comparisonToAverage': json['comparisonToAverage'] == null ? undefined : json['comparisonToAverage'],
        'waterFootprintL': json['waterFootprintL'] == null ? undefined : json['waterFootprintL'],
        'transportDistanceKm': json['transportDistanceKm'] == null ? undefined : json['transportDistanceKm'],
        'packagingScore': json['packagingScore'] == null ? undefined : json['packagingScore'],
        'ecoTips': json['ecoTips'] == null ? undefined : json['ecoTips'],
    };
}

export function SustainabilityAnalysisDtoToJSON(json: any): SustainabilityAnalysisDto {
    return SustainabilityAnalysisDtoToJSONTyped(json, false);
}

export function SustainabilityAnalysisDtoToJSONTyped(value?: SustainabilityAnalysisDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'co2Breakdown': value['co2Breakdown'] == null ? undefined : ((value['co2Breakdown'] as Array<any>).map(Co2BreakdownItemDtoToJSON)),
        'totalCo2Kg': value['totalCo2Kg'],
        'comparisonToAverage': value['comparisonToAverage'],
        'waterFootprintL': value['waterFootprintL'],
        'transportDistanceKm': value['transportDistanceKm'],
        'packagingScore': value['packagingScore'],
        'ecoTips': value['ecoTips'],
    };
}

