/* tslint:disable */
/* eslint-disable */
/**
 * AutexisCase.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemperatureLogDto
 */
export interface TemperatureLogDto {
    /**
     * 
     * @type {string}
     * @memberof TemperatureLogDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof TemperatureLogDto
     */
    time?: Date;
    /**
     * 
     * @type {number}
     * @memberof TemperatureLogDto
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof TemperatureLogDto
     */
    location?: string | null;
}

/**
 * Check if a given object implements the TemperatureLogDto interface.
 */
export function instanceOfTemperatureLogDto(value: object): value is TemperatureLogDto {
    return true;
}

export function TemperatureLogDtoFromJSON(json: any): TemperatureLogDto {
    return TemperatureLogDtoFromJSONTyped(json, false);
}

export function TemperatureLogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemperatureLogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'location': json['location'] == null ? undefined : json['location'],
    };
}

export function TemperatureLogDtoToJSON(json: any): TemperatureLogDto {
    return TemperatureLogDtoToJSONTyped(json, false);
}

export function TemperatureLogDtoToJSONTyped(value?: TemperatureLogDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'temperature': value['temperature'],
        'location': value['location'],
    };
}

